
test:
  name: energy-trading
  description: Executing the benchmark for match buyers and sellers
  workers:
    type: local
    number: 2
  rounds:
    - label: INITLEDGER and Stackelberg Game multiple users
      txDuration: 10
      rateControl:
        type: fixed-rate
        opts:
          transactionLoad: 20
      workload:
        module: workload/stackelbergGame2.js
        method: run
        arguments:
          contractId: smartcontract
        users: 10
    - label: Stackelberg Game
      txDuration: 50
      rateControl:
        type: fixed-rate
        opts:
          transactionLoad: 20
      workload:
        module: workload/energyworload2.js
        method: run
        arguments:
          contractId: smartcontract
        users: 10
monitor:
  type:
    - docker
  docker:
    containers:
      - all
    charting:
      polar:
        metrics: [all]
  interval: 1

